# Generated by Django 4.1.1 on 2022-10-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_delete_perdona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacimiento',
            field=models.DateTimeField(),
        ),
    ]
